import Head from 'next/head'
import Certificate from '../components/certificate'
import Footer from '../components/footer'
import Header from '../components/header'
import HeroSection from '../components/heroSection'
import OpenWallet from '../components/openWallet'
import Course from '../components/course'
import StartCourse from '../components/starteCourse'

export default function Home() {
  return (
    <div className='home flex justify-center  w-[200%] md:w-[100%] xl:w-full relative '>
           <div className="bg-gradient-to-br from-indigo-400 to-blue-300 w-[50%] h-[30rem] absolute -top-20 left-0 opacity-30 md:hidden -z-20 -mt-40 blur-2xl rounded-b-full"></div>
            <div className="bg-gradient-to-br from-indigo-400 to-blue-300 w-[40%] h-[30rem] -top-20 py-60 absolute right-0 opacity-30 md:hidden -z-20 -mt-40 blur-2xl rounded-b-full"></div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <section className='container  flex flex-col   '>

      <Header />
      <HeroSection />
      <OpenWallet />
      <Course />
      <Certificate />
      <StartCourse />
      <Footer />

      </section>

      

    
    </div>
  )
}
